### ISSUE TITLE
EPIC: Automated Testing for OCM CLI

### ISSUE THREAD

**Issue by robertwol** [open-component-model/ocm-project#103]
## Description

As a developer or contributor to the OCM project, I want to have automated testing in place to ensure the reliability and functionality of the OCM CLI and all its related components. This will help identify and fix issues early, improve code quality, ensure a proper release process and provide a robust user experience.

### List of Tasks
- [ ] Implement integration tests to cover all common use cases of OCM. At least all tests from [the current test framework](https://open-component-model.github.io/ocm-integrationtest/report.html?sort=result )should be included. One focus should be the `transfer`command as this implies actions on external registries of different kinds and actions with `--copy-resources`and `recursive` can result in large and long-running actions.
- [ ] Integrate the automated tests into the project's continuous integration (CI) pipeline and make a successful run mandatory for a successful merge.
- [ ] Integrate the test suite in the release action and make a successful run mandatory for a successful release.
- [ ] Establish a process for regularly updating and maintaining the automated tests as new features and changes are introduced.
- [ ] Define a baseline for performance tests
- [ ] Execute Performance Tests

### Definition of Done

- [ ] E2E tests cover a comprehensive range of OCM commands and their common variants.
- [ ] The testing framework is set up and integrated into the CI pipeline.
- [ ] The testing framework is set up and integrated into the release process.
- [ ] A process is established to update and maintain the automated tests regularly.

**Comment by Skarlso** [comment]
What remains to be done here? The integration test thingy is running and working, isn't it?

**Comment by jakobmoellerdev** [comment]
This has been open for so long that it is no longer in focus. We want to instead create a new conformance test matrix that will supercede the existing python test suite
