### ISSUE TITLE
Ensure Compliance and Security of OCM Core Tools and Controllers

### ISSUE THREAD

**Issue by morri-son** [open-component-model/ocm-project#165]
**Epic Description**

Ensure support for SOC, CyberEsentials, and FEDRAMP certification processes for OCM, its tooling  and controllers and ensure audit logging capability for both SAP and customers.  In addition to that Open Source security best practices should be applied for all GitHub repositories of the project.

##Related tasks:

- [ ] open-component-model/ocm-project#82
- [ ]  open-component-model/ocm-project#122
- [ ]  open-component-model/ocm-project#123
- [ ]  open-component-model/ocm-project#43

**Comment by morri-son** [comment]
duplicate of #164
