### ISSUE TITLE
EPIC: Enhance OCM CLI with additional uploaders

### ISSUE THREAD

**Issue by morri-son** [open-component-model/ocm-project#170]
The OCL CLI should be able to upload artifacts back into the same storage technology they have been pull from during a transfer. For Docker images this is built in already, several others are missing. Therefore we require to add missing technologies:

- npm
- maven

Relates issues:

- [x] https://github.com/open-component-model/ocm/issues/633
- [x] https://github.com/open-component-model/ocm-project/issues/28
- [x] https://github.com/open-component-model/ocm-project/issues/199
- [x] #200
