### ISSUE TITLE
EPIC: Align current architecture of OCM controllers / MPAS with new CNLM

### ISSUE THREAD

**Issue by morri-son** [open-component-model/ocm-project#207]
**Description**
Right now we have an overlap in functionality and processes our LM Tools offer and cover, OCM Controllers, MPAS (aka Deplomat) and Landscaper. All of them need to fit in the planned idea for a cloud-native lifecycle management (CNLM):

![CNLCM vision-Page-2](https://github.com/open-component-model/ocm-project/assets/67469729/ddda8d17-914a-4f80-9c0c-d3b73d11eaf7)

Required tasks and issues:

- [ ] Check and update documentation (in code and external) for OCM controllers and MPAS to enable others to understand concept, architecture and implementation
- [ ] Review architecture of OCM controllers / MPAS / Landscaper with the idea of using existing resources and controllers to build the new CNLM setup
- [ ] Create proposal for new design of resources and controllers for new CNLM setup

Related to #222

**Comment by morri-son** [comment]
@fabianburth I guess we can close this as this is part of the ADRs for controllers / meta controller, or?
