### ISSUE TITLE
Tidy root directory of ocm-repository

### ISSUE THREAD

**Issue by frewilhelm** [open-component-model/ocm-project#243]
**Description**

The root directory of the [ocm](https://github.com/open-component-model/ocm) repository is cluttered with files and directories.

As part of the Open-Source readiness initiative, the root directory should look well structured. To achieve this, we have to tidy up the repository - delete unused files and move the files to the place where they belong.

**TODO**
- [x] Delete [`sonar-project.properties`](https://github.com/open-component-model/ocm/blob/main/sonar-project.properties)
- [x] Move [`CODEOWNER`](https://github.com/open-component-model/ocm/blob/main/CODEOWNERS) to `.github` (see [doc](https://docs.github.com/de/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#codeowners-file-location))
- [ ] Move [`VERSION`](https://github.com/open-component-model/ocm/blob/main/VERSION) and [`version.go`](https://github.com/open-component-model/ocm/blob/main/version.go) if possible
- [x] Move [`https://github.com/open-component-model/ocm/blob/main/migrate.sh`](migrate.sh), [`https://github.com/open-component-model/ocm/blob/main/migrate.mig`](migrate.mig), and [`https://github.com/open-component-model/ocm/blob/main/migrate.md`](migrate.md)
- [ ] ...

If you see some more, please adjust the description

**Comment by morri-son** [comment]
we keep the VERSION file as is.
