### ISSUE TITLE
EPIC: UI to browse OCM repositories and their components

### ISSUE THREAD

**Issue by morri-son** [open-component-model/ocm-project#257]
**Description**
I as a consumer of services and products described via OCM components want to have a UI that allows various actions on all available OCM components:

- Display list of components
- Sort list of components by various criteria, e.g., alphabetical, date of add/change
- Filter / Search list of components by various criteria, e.g., alphabetical, date of add/change
- For a selected component, it should be possible to navigate into the content. The content should be showed grouped by resources, sources, componentReferences

**Done Criteria**
- [ ] ...
- [ ] Code has been reviewed by other team members
- [ ] Internal technical Documentation created/updated
- [ ] New / changed code is documented
- [ ] Analysis of existing tests (Unit and Integration)
- [ ] Unit Tests created for new code or existing Unit Tests updated
- [ ] Integration Test Suite updated (includes deletion of existing unnecessary Integration Test and/or creation of new ones if required)
- [ ] Enduser Documentation updated (if applicable)
- [ ] Successful demonstration in Review

**Comment by matthiasbruns** [comment]
Parallel with https://github.com/open-component-model/ocm-project/issues/640

**Comment by matthiasbruns** [comment]
Updated the EPIC during the Q1 planning in 2026

**Comment by matthiasbruns** [comment]
I think when https://github.com/open-component-model/ocm-project/issues/1001 lands, I will write a TUI cmd plugin prototype when there is time - I am really hyped for this
