### ISSUE TITLE
EPIC: Restructure OCM library

### ISSUE THREAD

**Issue by morri-son** [open-component-model/ocm-project#27]
**Description**
The OCM library should be restructured, to enable better discovery and encapsulate functionality in smaller parts. This should allow collaboration with and onboarding of new people to the project. The restructuring  should happen on package, module and repository level. The restructuring on package and module level should happen at the same time, a separation of the current repository "ocm" into multiple other repositories should happen afterwards.

Together with the restructuring the modules should change names from "github.com" to the "ocm.software" domain if this is technically feasible.

The current proposal for a new package structure can be found [here](https://sap-my.sharepoint.com/:w:/p/hilmar_falkenberg/EYsKcXg7iGJJqnCZvqvYRxYBTp1zMCCcrqhHg2kJb7R7kQ?wdLOR=c3C1A1141-5087-B648-B5E7-7004732F667A)

Linked issues:

- [x] open-component-model/ocm-project#26 
- [x] open-component-model/ocm-project#25
- [x] open-component-model/ocm/pull/741

Linked epics:
- [ ] open-component-model/ocm-project#125 

**Done Criteria**
- [x] All subtasks from above are done
- [x] Successful demonstration/discussion in Review
