### ISSUE TITLE
EPIC: Resource Controller

### ISSUE THREAD

**Issue by morri-son** [open-component-model/ocm-project#278]
**Description**
Add a new controller to the set of existing OCM controllers which handles Resources.

**Done Criteria**
- [x] Code has been reviewed by other team members
- [x] Internal technical Documentation created/updated
- [x] New / changed code is documented
- [x] Analysis of existing tests (Unit and Integration)
- [x] Unit Tests created for new code or existing Unit Tests updated
- [x] Integration Test Suite updated (includes deletion of existing unnecessary Integration Test and/or creation of new ones if required)
- [ ] Enduser Documentation updated (if applicable)
- [x] Successful demonstration in Review

**Comment by jakobmoellerdev** [comment]
Closing as completed. The resource controller is present and working as intended. We still need to add separate end user docs but thats only when we have the website ready
