### ISSUE TITLE
Refactor the OCM library

### ISSUE THREAD

**Issue by morri-son** [open-component-model/ocm-project#39]
# Epic: Refactor the OCM library

## Description 
To get the OCM project ready for the next phase of adoption, which targets both, commercial players and other opensource projects, the OCM library should be refactored. This is essential to keep the current momentum, but also to keep the project alive over a longer time and to quickly attract more people to contribute to the project.
 
## The goals for refactoring are:
 
- Define public API (aka v2)
- Create a graphical overview of the API to be able to better discuss the new API 
- Try to return concrete types, not interfaces
- Ensure the code and its structure are easy accessible to and understandable by newcomers
- Each function and package has documentation and examples
- Do not force technology choices on users through dependencies (e.g. gingko in env package)
- Define/capture areas where extensibility is necessary
- Respect the original design goals
 
A topic that needs to be decided before going on is if the OCM CLI as reference implementation of the OCM library should stay in the ocm repository or if it should be moved to an own, dedicated GitHub repository. 
 
### Steps for the refactoring
 
-	Definition of public API aka v2 under github.com/open-component-model/ocm/v2
-	Rewire existing v1 functionality to v2
-	(Move CLI to dedicated repository github.com/open-component-model/ocmcli) <-- decision pending
-	Refactor CLI so that it only consumes v2
-	Gradually replace v1 wirings with new v2 implementation
 
## Existing issues from OCM simplification workshop related to the OCM lib (to be checked if still valid)

- [ ] open-component-model/ocm-project#120 
- [ ] open-component-model/ocm-project#114 
- [x] open-component-model/ocm-project#106 
- [ ] open-component-model/ocm-project#102 
- [x] open-component-model/ocm-project#100
- [ ] open-component-model/ocm-project#44

**Comment by morri-son** [comment]
remove EPIC and just keep distinct issues in backlog.
